FROM golang:1.23-bookworm

RUN go install github.com/air-verse/air@v1.61.7 \
    && go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.28.0 \
    && go install golang.org/x/tools/cmd/goimports@v0.25.0 \
    && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

WORKDIR /workspace
