FROM golang:1.23-bookworm

RUN go install github.com/air-verse/air@v1.61.7 \
    && go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.28.0 \
    && go install golang.org/x/tools/cmd/goimports@v0.25.0 \
    && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0 \
    && go install golang.org/x/vuln/cmd/govulncheck@v1.1.4 \
    && go install github.com/anchore/syft/cmd/syft@v1.18.1 \
    && go install github.com/gitleaks/gitleaks/v8@v8.24.2

WORKDIR /workspace
