DROP TRIGGER IF EXISTS issues_site_assignments_trigger ON issues;
DROP FUNCTION IF EXISTS enforce_issue_site_assignments();
DROP INDEX IF EXISTS idx_issues_assigned_team;
DROP INDEX IF EXISTS idx_issues_assignee;
DROP INDEX IF EXISTS idx_issues_site_visibility;
ALTER TABLE issues DROP CONSTRAINT IF EXISTS issues_visibility_class_check;
ALTER TABLE issues DROP CONSTRAINT IF EXISTS issues_site_id_fkey;
ALTER TABLE issues DROP COLUMN IF EXISTS visibility_class;
ALTER TABLE issues DROP COLUMN IF EXISTS assigned_team_id;
ALTER TABLE issues DROP COLUMN IF EXISTS assignee_id;
ALTER TABLE issues DROP COLUMN IF EXISTS site_id;
DROP INDEX IF EXISTS idx_team_memberships_user;
DROP TABLE IF EXISTS team_memberships;
DROP INDEX IF EXISTS idx_teams_site;
DROP TABLE IF EXISTS teams;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_site_id_fkey;
ALTER TABLE users DROP COLUMN IF EXISTS site_id;
DROP INDEX IF EXISTS idx_users_site;
ALTER TABLE locations DROP CONSTRAINT IF EXISTS locations_site_id_fkey;
ALTER TABLE locations DROP COLUMN IF EXISTS site_id;
DROP INDEX IF EXISTS idx_locations_site;
DROP TABLE IF EXISTS sites;
