export type PackKey = "ALL" | "GARMENT" | "MACHINERY" | "ELECTRONICS";

export const PACKS: Record<Exclude<PackKey, "ALL">, Record<string, true>> = {
  GARMENT: Object.fromEntries(
    [
      "scrap_material",
      "broken_equipment",
      "blocked_aisle",
      "missing_demarcation",
      "wrong_tool_place",
      "tangled_cables",
      "dust_accumulation",
      "scattered_trash",
      "oil_leak",
      "dirty_light_fixtures",
      "missing_label",
      "ppe_violation",
      "safety_gear",
      "fire_hazard",
      "exposed_wire",
      "slippery_floor",
    ].map((code) => [code, true]),
  ),
  MACHINERY: Object.fromEntries(
    [
      "scrap_material",
      "unneeded_tools",
      "expired_chemical",
      "broken_equipment",
      "blocked_aisle",
      "missing_demarcation",
      "wrong_tool_place",
      "tangled_cables",
      "stack_too_high",
      "oil_leak",
      "dust_accumulation",
      "dirty_workstation",
      "stained_floor",
      "dirty_electrical_panel",
      "missing_label",
      "broken_gauge",
      "missing_calibration",
      "sop_noncompliance",
      "safety_gear",
      "fire_hazard",
      "exposed_wire",
      "slippery_floor",
      "missing_machine_guard",
      "chemical_spill",
      "emergency_stop_fault",
      "gas_cylinder_unsecured",
      "forklift_speeding",
    ].map((code) => [code, true]),
  ),
  ELECTRONICS: Object.fromEntries(
    [
      "scrap_material",
      "unneeded_tools",
      "stagnant_wip",
      "excess_inventory",
      "blocked_aisle",
      "missing_demarcation",
      "wrong_tool_place",
      "tangled_cables",
      "unlabeled_container",
      "dust_accumulation",
      "scattered_trash",
      "dirty_workstation",
      "dirty_light_fixtures",
      "missing_label",
      "broken_gauge",
      "missing_calibration",
      "faded_standard",
      "ppe_violation",
      "sop_noncompliance",
      "safety_gear",
      "fire_hazard",
      "exposed_wire",
      "missing_machine_guard",
      "chemical_spill",
      "overloaded_socket",
    ].map((code) => [code, true]),
  ),
};
