// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role, permission_code)
VALUES ($1, $2)
ON CONFLICT (role, permission_code) DO NOTHING
`

type AddRolePermissionParams struct {
	Role           string
	PermissionCode string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, addRolePermission, arg.Role, arg.PermissionCode)
	return err
}

const claimOutboxTasks = `-- name: ClaimOutboxTasks :many
UPDATE notification_outbox
SET status = 'SENDING',
    next_retry_at = CURRENT_TIMESTAMP + INTERVAL '120 seconds'
WHERE id IN (
    SELECT id FROM notification_outbox
    WHERE (status = 'PENDING' AND next_retry_at <= CURRENT_TIMESTAMP)
       OR (status = 'SENDING' AND next_retry_at < CURRENT_TIMESTAMP)
    ORDER BY id ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, issue_id, event_type, channel, payload, status, retry_count, max_retries, last_error, next_retry_at, created_at, sent_at
`

func (q *Queries) ClaimOutboxTasks(ctx context.Context, limit int32) ([]NotificationOutbox, error) {
	rows, err := q.db.QueryContext(ctx, claimOutboxTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.EventType,
			&i.Channel,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOldAuditLogs = `-- name: CleanupOldAuditLogs :exec
DELETE FROM system_audit_logs
WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '3 years'
`

func (q *Queries) CleanupOldAuditLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOldAuditLogs)
	return err
}

const closeIssue = `-- name: CloseIssue :one
UPDATE issues
SET status = 'CLOSED',
    score_rating = $2,
    closed_at = CURRENT_TIMESTAMP,
    version = version + 1
WHERE id = $1 
  AND status = 'PENDING_REVIEW' 
  AND ($3::int IS NULL OR version = $3)
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type CloseIssueParams struct {
	ID              int64
	ScoreRating     sql.NullInt16
	ExpectedVersion sql.NullInt32
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, closeIssue, arg.ID, arg.ScoreRating, arg.ExpectedVersion)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users
WHERE role = 'ADMIN' AND is_active = TRUE
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesFiltered = `-- name: CountIssuesFiltered :one
SELECT COUNT(*) FROM issues
WHERE (coalesce(cardinality($1::varchar[]), 0) = 0 OR status = ANY($1::varchar[]))
  AND (coalesce(cardinality($2::varchar[]), 0) = 0 OR category = ANY($2::varchar[]))
  AND (coalesce(cardinality($3::varchar[]), 0) = 0 OR location_code = ANY($3::varchar[]))
`

type CountIssuesFilteredParams struct {
	Statuses      []string
	Categories    []string
	LocationCodes []string
}

func (q *Queries) CountIssuesFiltered(ctx context.Context, arg CountIssuesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesFiltered, pq.Array(arg.Statuses), pq.Array(arg.Categories), pq.Array(arg.LocationCodes))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenIssuesByLocation = `-- name: CountOpenIssuesByLocation :one
SELECT COUNT(*)::bigint AS open_count
FROM issues
WHERE location_code = $1
  AND status = 'OPEN'
`

func (q *Queries) CountOpenIssuesByLocation(ctx context.Context, locationCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenIssuesByLocation, locationCode)
	var open_count int64
	err := row.Scan(&open_count)
	return open_count, err
}

const countOverdueIssuesByLocation = `-- name: CountOverdueIssuesByLocation :one
SELECT COUNT(*)::bigint AS overdue_count
FROM issues
WHERE location_code = $1
  AND status = 'OPEN'
  AND created_at < CURRENT_TIMESTAMP - INTERVAL '48 hours'
`

func (q *Queries) CountOverdueIssuesByLocation(ctx context.Context, locationCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOverdueIssuesByLocation, locationCode)
	var overdue_count int64
	err := row.Scan(&overdue_count)
	return overdue_count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (
    client_uuid, version, creator_id, category, cause_type, location_code, description, photo_before, photo_detail, status
) VALUES (
    $1, 1, $2, $3, $4, $5, $6, $7, $8, 'OPEN'
)
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type CreateIssueParams struct {
	ClientUuid   string
	CreatorID    int64
	Category     string
	CauseType    string
	LocationCode string
	Description  sql.NullString
	PhotoBefore  string
	PhotoDetail  sql.NullString
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue,
		arg.ClientUuid,
		arg.CreatorID,
		arg.Category,
		arg.CauseType,
		arg.LocationCode,
		arg.Description,
		arg.PhotoBefore,
		arg.PhotoDetail,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createLocalAdmin = `-- name: CreateLocalAdmin :one
INSERT INTO users (
    username, password_hash, auth_source, full_name, email, role, is_active
) VALUES (
    $1, $2, 'LOCAL', $3, $4, 'ADMIN', TRUE
)
RETURNING id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at
`

type CreateLocalAdminParams struct {
	Username     string
	PasswordHash sql.NullString
	FullName     string
	Email        sql.NullString
}

func (q *Queries) CreateLocalAdmin(ctx context.Context, arg CreateLocalAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createLocalAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
    code, name_vi, name_zh, name_en, qr_code, is_active
) VALUES (
    $1, $2, $3, $4, $5, TRUE
)
RETURNING id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at
`

type CreateLocationParams struct {
	Code   string
	NameVi string
	NameZh string
	NameEn string
	QrCode string
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.Code,
		arg.NameVi,
		arg.NameZh,
		arg.NameEn,
		arg.QrCode,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.QrCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createOutboxEntry = `-- name: CreateOutboxEntry :one
INSERT INTO notification_outbox (
    issue_id, event_type, channel, payload, status, next_retry_at
) VALUES (
    $1, $2, $3, $4, 'PENDING', CURRENT_TIMESTAMP
)
RETURNING id, issue_id, event_type, channel, payload, status, retry_count, max_retries, last_error, next_retry_at, created_at, sent_at
`

type CreateOutboxEntryParams struct {
	IssueID   int64
	EventType string
	Channel   string
	Payload   json.RawMessage
}

func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (NotificationOutbox, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEntry,
		arg.IssueID,
		arg.EventType,
		arg.Channel,
		arg.Payload,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.EventType,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token_hash, device_info, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, token_hash, device_info, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID     int64
	TokenHash  string
	DeviceInfo sql.NullString
	ExpiresAt  time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserJIT = `-- name: CreateUserJIT :one
INSERT INTO users (
    username, auth_source, ad_dn, full_name, email, role, is_active, last_login_at
) VALUES (
    $1, 'AD', $2, $3, $4, $5, TRUE, CURRENT_TIMESTAMP
)
RETURNING id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at
`

type CreateUserJITParams struct {
	Username string
	AdDn     sql.NullString
	FullName string
	Email    sql.NullString
	Role     string
}

func (q *Queries) CreateUserJIT(ctx context.Context, arg CreateUserJITParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserJIT,
		arg.Username,
		arg.AdDn,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteIssueTags = `-- name: DeleteIssueTags :exec
DELETE FROM issue_tags
WHERE issue_id = $1
`

func (q *Queries) DeleteIssueTags(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueTags, issueID)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, role string) error {
	_, err := q.db.ExecContext(ctx, deleteRolePermissions, role)
	return err
}

const forceResolveIssue = `-- name: ForceResolveIssue :one
UPDATE issues
SET status = 'PENDING_REVIEW',
    resolver_id = $2,
    photo_after = $3,
    resolved_at = CURRENT_TIMESTAMP,
    version = version + 1
WHERE id = $1
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type ForceResolveIssueParams struct {
	ID         int64
	ResolverID sql.NullInt64
	PhotoAfter sql.NullString
}

func (q *Queries) ForceResolveIssue(ctx context.Context, arg ForceResolveIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, forceResolveIssue, arg.ID, arg.ResolverID, arg.PhotoAfter)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getADConfig = `-- name: GetADConfig :one
SELECT id, is_enabled, server, port, use_tls, skip_tls_verify, base_dn, bind_dn, bind_password, user_filter, group_admin_dn, group_safety_dn, group_leader_dn, updated_at, updated_by FROM ad_configs
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetADConfig(ctx context.Context) (AdConfig, error) {
	row := q.db.QueryRowContext(ctx, getADConfig)
	var i AdConfig
	err := row.Scan(
		&i.ID,
		&i.IsEnabled,
		&i.Server,
		&i.Port,
		&i.UseTls,
		&i.SkipTlsVerify,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPassword,
		&i.UserFilter,
		&i.GroupAdminDn,
		&i.GroupSafetyDn,
		&i.GroupLeaderDn,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAIConfig = `-- name: GetAIConfig :one
SELECT id, is_enabled, base_url, api_key, default_model, model_translate, model_vision, model_summary, updated_at, updated_by FROM ai_configs
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetAIConfig(ctx context.Context) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getAIConfig)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.DefaultModel,
		&i.ModelTranslate,
		&i.ModelVision,
		&i.ModelSummary,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT 
    category,
    COUNT(*)::bigint AS count
FROM issues
GROUP BY category
ORDER BY category ASC
`

type GetCategoryBreakdownRow struct {
	Category string
	Count    int64
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at FROM issues
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueByUUID = `-- name: GetIssueByUUID :one
SELECT id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at FROM issues
WHERE client_uuid = $1 LIMIT 1
`

func (q *Queries) GetIssueByUUID(ctx context.Context, clientUuid string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByUUID, clientUuid)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueTrends = `-- name: GetIssueTrends :many
SELECT 
    d.day::date AS date_key,
    COUNT(CASE WHEN i.created_at::date = d.day::date THEN 1 END)::bigint AS created_count,
    COUNT(CASE WHEN (i.closed_at::date = d.day::date OR (i.closed_at IS NULL AND i.resolved_at::date = d.day::date)) THEN 1 END)::bigint AS resolved_count
FROM generate_series(
    CURRENT_DATE - ($1::int - 1) * INTERVAL '1 day',
    CURRENT_DATE,
    INTERVAL '1 day'
) AS d(day)
LEFT JOIN issues i ON (
    i.created_at::date = d.day::date 
    OR i.closed_at::date = d.day::date 
    OR (i.closed_at IS NULL AND i.resolved_at::date = d.day::date)
)
GROUP BY d.day
ORDER BY d.day ASC
`

type GetIssueTrendsRow struct {
	DateKey       time.Time
	CreatedCount  int64
	ResolvedCount int64
}

func (q *Queries) GetIssueTrends(ctx context.Context, dollar_1 int32) ([]GetIssueTrendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIssueTrends, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIssueTrendsRow
	for rows.Next() {
		var i GetIssueTrendsRow
		if err := rows.Scan(&i.DateKey, &i.CreatedCount, &i.ResolvedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastCronTaskLog = `-- name: GetLastCronTaskLog :one
SELECT id, task_name, last_run_at, status, details FROM cron_task_logs
WHERE task_name = $1
ORDER BY last_run_at DESC
LIMIT 1
`

func (q *Queries) GetLastCronTaskLog(ctx context.Context, taskName string) (CronTaskLog, error) {
	row := q.db.QueryRowContext(ctx, getLastCronTaskLog, taskName)
	var i CronTaskLog
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.LastRunAt,
		&i.Status,
		&i.Details,
	)
	return i, err
}

const getLocationByCode = `-- name: GetLocationByCode :one
SELECT id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at FROM locations
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetLocationByCode(ctx context.Context, code string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByCode, code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.QrCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationLeaderboardStats = `-- name: GetLocationLeaderboardStats :many
WITH score_totals AS (
    SELECT target_id AS location_code, COALESCE(SUM(points), 0)::bigint AS sum_points
    FROM score_logs
    WHERE target_type = 'LOCATION' AND score_logs.created_at >= $1
    GROUP BY target_id
), issue_totals AS (
    SELECT location_code,
           COUNT(*) FILTER (WHERE status = 'OPEN')::bigint AS open_count,
           COUNT(*) FILTER (WHERE status = 'OPEN' AND issues.created_at < CURRENT_TIMESTAMP - INTERVAL '48 hours')::bigint AS overdue_count
    FROM issues
    GROUP BY location_code
)
SELECT l.code AS location_code,
       l.name_vi AS location_name,
       COALESCE(st.sum_points, 0)::bigint AS sum_points,
       COALESCE(it.open_count, 0)::bigint AS open_count,
       COALESCE(it.overdue_count, 0)::bigint AS overdue_count
FROM locations l
LEFT JOIN score_totals st ON st.location_code = l.code
LEFT JOIN issue_totals it ON it.location_code = l.code
WHERE l.is_active = TRUE
ORDER BY l.code
`

type GetLocationLeaderboardStatsRow struct {
	LocationCode string
	LocationName string
	SumPoints    int64
	OpenCount    int64
	OverdueCount int64
}

func (q *Queries) GetLocationLeaderboardStats(ctx context.Context, createdAt time.Time) ([]GetLocationLeaderboardStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocationLeaderboardStats, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationLeaderboardStatsRow
	for rows.Next() {
		var i GetLocationLeaderboardStatsRow
		if err := rows.Scan(
			&i.LocationCode,
			&i.LocationName,
			&i.SumPoints,
			&i.OpenCount,
			&i.OverdueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationScoreSumInWeek = `-- name: GetLocationScoreSumInWeek :one
SELECT COALESCE(SUM(points), 0)::bigint AS sum_points
FROM score_logs
WHERE target_type = 'LOCATION'
  AND target_id = $1
  AND created_at >= $2
`

type GetLocationScoreSumInWeekParams struct {
	TargetID  string
	CreatedAt time.Time
}

func (q *Queries) GetLocationScoreSumInWeek(ctx context.Context, arg GetLocationScoreSumInWeekParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLocationScoreSumInWeek, arg.TargetID, arg.CreatedAt)
	var sum_points int64
	err := row.Scan(&sum_points)
	return sum_points, err
}

const getNotificationConfig = `-- name: GetNotificationConfig :one
SELECT id, wxpusher_enabled, wxpusher_app_token, lan_webhook_url, public_base_url, updated_at, updated_by FROM notification_configs
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetNotificationConfig(ctx context.Context) (NotificationConfig, error) {
	row := q.db.QueryRowContext(ctx, getNotificationConfig)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.WxpusherEnabled,
		&i.WxpusherAppToken,
		&i.LanWebhookUrl,
		&i.PublicBaseUrl,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_info, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReportKPISummary = `-- name: GetReportKPISummary :one
SELECT 
    COUNT(*)::bigint AS total_issues,
    COUNT(CASE WHEN status = 'OPEN' THEN 1 END)::bigint AS open_issues,
    COUNT(CASE WHEN status = 'PENDING_REVIEW' THEN 1 END)::bigint AS pending_review_issues,
    COUNT(CASE WHEN status = 'CLOSED' THEN 1 END)::bigint AS closed_issues,
    COUNT(CASE WHEN status = 'INVALID' THEN 1 END)::bigint AS invalid_issues,
    COUNT(CASE WHEN category = '6S' AND status != 'CLOSED' THEN 1 END)::bigint AS safety_issues,
    COUNT(CASE WHEN status = 'OPEN' AND created_at < CURRENT_TIMESTAMP - INTERVAL '48 hours' THEN 1 END)::bigint AS overdue_issues
FROM issues
`

type GetReportKPISummaryRow struct {
	TotalIssues         int64
	OpenIssues          int64
	PendingReviewIssues int64
	ClosedIssues        int64
	InvalidIssues       int64
	SafetyIssues        int64
	OverdueIssues       int64
}

func (q *Queries) GetReportKPISummary(ctx context.Context) (GetReportKPISummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getReportKPISummary)
	var i GetReportKPISummaryRow
	err := row.Scan(
		&i.TotalIssues,
		&i.OpenIssues,
		&i.PendingReviewIssues,
		&i.ClosedIssues,
		&i.InvalidIssues,
		&i.SafetyIssues,
		&i.OverdueIssues,
	)
	return i, err
}

const getReporterLeaderboardInMonth = `-- name: GetReporterLeaderboardInMonth :many
SELECT u.id AS user_id,
       u.full_name,
       COALESCE(SUM(sl.points), 0)::bigint AS points,
       COUNT(DISTINCT CASE WHEN i.status = 'CLOSED' THEN i.id END)::bigint AS valid_count,
       COUNT(DISTINCT CASE WHEN i.status = 'CLOSED' AND i.category = '6S' THEN i.id END)::bigint AS safety_count
FROM users u
JOIN score_logs sl ON sl.target_type = 'USER' AND sl.target_id = u.id::varchar
LEFT JOIN issues i ON i.id = sl.issue_id
WHERE sl.created_at >= $1
GROUP BY u.id, u.full_name
ORDER BY points DESC, valid_count DESC, u.id ASC
LIMIT 50
`

type GetReporterLeaderboardInMonthRow struct {
	UserID      int64
	FullName    string
	Points      int64
	ValidCount  int64
	SafetyCount int64
}

func (q *Queries) GetReporterLeaderboardInMonth(ctx context.Context, createdAt time.Time) ([]GetReporterLeaderboardInMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getReporterLeaderboardInMonth, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReporterLeaderboardInMonthRow
	for rows.Next() {
		var i GetReporterLeaderboardInMonthRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Points,
			&i.ValidCount,
			&i.SafetyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoringRuleByKey = `-- name: GetScoringRuleByKey :one
SELECT id, rule_key, points, description FROM scoring_rules
WHERE rule_key = $1 LIMIT 1
`

func (q *Queries) GetScoringRuleByKey(ctx context.Context, ruleKey string) (ScoringRule, error) {
	row := q.db.QueryRowContext(ctx, getScoringRuleByKey, ruleKey)
	var i ScoringRule
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const getScoringRules = `-- name: GetScoringRules :many
SELECT id, rule_key, points, description FROM scoring_rules
ORDER BY id ASC
`

func (q *Queries) GetScoringRules(ctx context.Context) ([]ScoringRule, error) {
	rows, err := q.db.QueryContext(ctx, getScoringRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoringRule
	for rows.Next() {
		var i ScoringRule
		if err := rows.Scan(
			&i.ID,
			&i.RuleKey,
			&i.Points,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopViolatedTags = `-- name: GetTopViolatedTags :many
SELECT 
    t.code AS tag_code,
    t.category,
    t.name_vi,
    t.name_zh,
    t.name_en,
    COUNT(it.issue_id)::bigint AS violation_count
FROM issue_tags it
JOIN tags t ON it.tag_code = t.code
GROUP BY t.code, t.category, t.name_vi, t.name_zh, t.name_en
ORDER BY violation_count DESC, t.code ASC
LIMIT $1
`

type GetTopViolatedTagsRow struct {
	TagCode        string
	Category       string
	NameVi         string
	NameZh         string
	NameEn         string
	ViolationCount int64
}

func (q *Queries) GetTopViolatedTags(ctx context.Context, limit int32) ([]GetTopViolatedTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopViolatedTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopViolatedTagsRow
	for rows.Next() {
		var i GetTopViolatedTagsRow
		if err := rows.Scan(
			&i.TagCode,
			&i.Category,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.ViolationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslationCache = `-- name: GetTranslationCache :one
SELECT content_hash, target_lang, source_text, translated_text, created_at
FROM translation_cache
WHERE content_hash = $1 AND target_lang = $2
`

type GetTranslationCacheParams struct {
	ContentHash string
	TargetLang  string
}

func (q *Queries) GetTranslationCache(ctx context.Context, arg GetTranslationCacheParams) (TranslationCache, error) {
	row := q.db.QueryRowContext(ctx, getTranslationCache, arg.ContentHash, arg.TargetLang)
	var i TranslationCache
	err := row.Scan(
		&i.ContentHash,
		&i.TargetLang,
		&i.SourceText,
		&i.TranslatedText,
		&i.CreatedAt,
	)
	return i, err
}

const getTranslationCacheBatch = `-- name: GetTranslationCacheBatch :many
SELECT content_hash, translated_text
FROM translation_cache
WHERE content_hash = ANY($1::varchar[]) AND target_lang = $2
`

type GetTranslationCacheBatchParams struct {
	ContentHashes []string
	TargetLang    string
}

type GetTranslationCacheBatchRow struct {
	ContentHash    string
	TranslatedText string
}

func (q *Queries) GetTranslationCacheBatch(ctx context.Context, arg GetTranslationCacheBatchParams) ([]GetTranslationCacheBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getTranslationCacheBatch, pq.Array(arg.ContentHashes), arg.TargetLang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranslationCacheBatchRow
	for rows.Next() {
		var i GetTranslationCacheBatchRow
		if err := rows.Scan(&i.ContentHash, &i.TranslatedText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByBadgeCode = `-- name: GetUserByBadgeCode :one
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE badge_code = $1 LIMIT 1
`

func (q *Queries) GetUserByBadgeCode(ctx context.Context, badgeCode sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByBadgeCode, badgeCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT rp.permission_code
FROM role_permissions rp
JOIN users u ON u.role = rp.role
WHERE u.id = $1
ORDER BY rp.permission_code ASC
`

func (q *Queries) GetUserPermissions(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTagUseCount = `-- name: IncrementTagUseCount :exec
UPDATE tags
SET use_count = use_count + 1
WHERE code = $1
`

func (q *Queries) IncrementTagUseCount(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, incrementTagUseCount, code)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO system_audit_logs (
    user_id, action, target_table, target_id, old_value, new_value, ip_address, user_agent, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP
)
`

type InsertAuditLogParams struct {
	UserID      sql.NullInt64
	Action      string
	TargetTable string
	TargetID    string
	OldValue    json.RawMessage
	NewValue    json.RawMessage
	IpAddress   sql.NullString
	UserAgent   sql.NullString
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.TargetTable,
		arg.TargetID,
		arg.OldValue,
		arg.NewValue,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertCronTaskLog = `-- name: InsertCronTaskLog :one
INSERT INTO cron_task_logs (
    task_name, last_run_at, status, details
) VALUES (
    $1, CURRENT_TIMESTAMP, $2, $3
)
RETURNING id, task_name, last_run_at, status, details
`

type InsertCronTaskLogParams struct {
	TaskName string
	Status   string
	Details  sql.NullString
}

func (q *Queries) InsertCronTaskLog(ctx context.Context, arg InsertCronTaskLogParams) (CronTaskLog, error) {
	row := q.db.QueryRowContext(ctx, insertCronTaskLog, arg.TaskName, arg.Status, arg.Details)
	var i CronTaskLog
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.LastRunAt,
		&i.Status,
		&i.Details,
	)
	return i, err
}

const insertIssueTag = `-- name: InsertIssueTag :exec
INSERT INTO issue_tags (
    issue_id, tag_code
) VALUES (
    $1, $2
) ON CONFLICT DO NOTHING
`

type InsertIssueTagParams struct {
	IssueID int64
	TagCode string
}

func (q *Queries) InsertIssueTag(ctx context.Context, arg InsertIssueTagParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueTag, arg.IssueID, arg.TagCode)
	return err
}

const insertScoreLog = `-- name: InsertScoreLog :exec
INSERT INTO score_logs (
    issue_id, target_type, target_id, rule_key, points, created_at, penalty_date
) VALUES (
    $1, $2, $3, $4, $5, CURRENT_TIMESTAMP, $6
)
`

type InsertScoreLogParams struct {
	IssueID     int64
	TargetType  string
	TargetID    string
	RuleKey     string
	Points      int32
	PenaltyDate sql.NullTime
}

func (q *Queries) InsertScoreLog(ctx context.Context, arg InsertScoreLogParams) error {
	_, err := q.db.ExecContext(ctx, insertScoreLog,
		arg.IssueID,
		arg.TargetType,
		arg.TargetID,
		arg.RuleKey,
		arg.Points,
		arg.PenaltyDate,
	)
	return err
}

const invalidateIssue = `-- name: InvalidateIssue :one
UPDATE issues
SET status = 'INVALID',
    reject_reason = $2,
    version = version + 1
WHERE id = $1 
  AND status IN ('OPEN', 'PENDING_REVIEW') 
  AND ($3::int IS NULL OR version = $3)
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type InvalidateIssueParams struct {
	ID              int64
	RejectReason    sql.NullString
	ExpectedVersion sql.NullInt32
}

func (q *Queries) InvalidateIssue(ctx context.Context, arg InvalidateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, invalidateIssue, arg.ID, arg.RejectReason, arg.ExpectedVersion)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listAllActivePhotoBasenames = `-- name: ListAllActivePhotoBasenames :many
SELECT photo_before AS photo_name FROM issues WHERE photo_before != ''
UNION
SELECT photo_detail AS photo_name FROM issues WHERE photo_detail IS NOT NULL AND photo_detail != ''
UNION
SELECT photo_after AS photo_name FROM issues WHERE photo_after IS NOT NULL AND photo_after != ''
`

func (q *Queries) ListAllActivePhotoBasenames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllActivePhotoBasenames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var photo_name string
		if err := rows.Scan(&photo_name); err != nil {
			return nil, err
		}
		items = append(items, photo_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllLocations = `-- name: ListAllLocations :many
SELECT id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at FROM locations
ORDER BY code ASC
`

// Returns all locations including inactive ones for admin management
func (q *Queries) ListAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.QrCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, code, name_vi, name_zh, name_en, category, use_count, is_preset, is_active FROM tags
ORDER BY use_count DESC, id ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.Category,
			&i.UseCount,
			&i.IsPreset,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesFiltered = `-- name: ListIssuesFiltered :many
SELECT i.id, i.client_uuid, i.version, i.creator_id, i.resolver_id, i.category, i.cause_type, i.location_code, i.description, i.reject_reason, i.photo_before, i.photo_detail, i.photo_after, i.score_rating, i.status, i.created_at, i.resolved_at, i.closed_at, 
       COALESCE((
           SELECT SUM(CASE WHEN sl.points < 0 THEN -sl.points ELSE 0 END)
           FROM score_logs sl
           WHERE sl.issue_id = i.id
       ), 0)::bigint AS score_deducted,
       loc.name_vi AS location_name_vi,
       u.username AS creator_username,
       u.full_name AS creator_full_name,
       res.username AS resolver_username,
       res.full_name AS resolver_full_name
FROM issues i
JOIN locations loc ON i.location_code = loc.code
JOIN users u ON i.creator_id = u.id
LEFT JOIN users res ON i.resolver_id = res.id
WHERE (coalesce(cardinality($1::varchar[]), 0) = 0 OR i.status = ANY($1::varchar[]))
  AND (coalesce(cardinality($2::varchar[]), 0) = 0 OR i.category = ANY($2::varchar[]))
  AND (coalesce(cardinality($3::varchar[]), 0) = 0 OR i.location_code = ANY($3::varchar[]))
ORDER BY 
    CASE WHEN i.category = '6S' THEN 0 ELSE 1 END,
    i.created_at DESC
LIMIT $5 OFFSET $4
`

type ListIssuesFilteredParams struct {
	Statuses      []string
	Categories    []string
	LocationCodes []string
	Offset        int32
	Limit         int32
}

type ListIssuesFilteredRow struct {
	ID               int64
	ClientUuid       string
	Version          int32
	CreatorID        int64
	ResolverID       sql.NullInt64
	Category         string
	CauseType        string
	LocationCode     string
	Description      sql.NullString
	RejectReason     sql.NullString
	PhotoBefore      string
	PhotoDetail      sql.NullString
	PhotoAfter       sql.NullString
	ScoreRating      sql.NullInt16
	Status           string
	CreatedAt        time.Time
	ResolvedAt       sql.NullTime
	ClosedAt         sql.NullTime
	ScoreDeducted    int64
	LocationNameVi   string
	CreatorUsername  string
	CreatorFullName  string
	ResolverUsername sql.NullString
	ResolverFullName sql.NullString
}

func (q *Queries) ListIssuesFiltered(ctx context.Context, arg ListIssuesFilteredParams) ([]ListIssuesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesFiltered,
		pq.Array(arg.Statuses),
		pq.Array(arg.Categories),
		pq.Array(arg.LocationCodes),
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesFilteredRow
	for rows.Next() {
		var i ListIssuesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientUuid,
			&i.Version,
			&i.CreatorID,
			&i.ResolverID,
			&i.Category,
			&i.CauseType,
			&i.LocationCode,
			&i.Description,
			&i.RejectReason,
			&i.PhotoBefore,
			&i.PhotoDetail,
			&i.PhotoAfter,
			&i.ScoreRating,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.ScoreDeducted,
			&i.LocationNameVi,
			&i.CreatorUsername,
			&i.CreatorFullName,
			&i.ResolverUsername,
			&i.ResolverFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForExport = `-- name: ListIssuesForExport :many
SELECT 
    i.id,
    i.client_uuid,
    i.category,
    i.location_code,
    loc.name_vi AS location_name_vi,
    loc.name_zh AS location_name_zh,
    loc.name_en AS location_name_en,
    i.status,
    i.description,
    i.reject_reason,
    u.username AS creator_username,
    u.full_name AS creator_full_name,
    res.username AS resolver_username,
    res.full_name AS resolver_full_name,
    i.score_rating,
    i.created_at,
    i.resolved_at,
    i.closed_at,
    COALESCE(STRING_AGG(it.tag_code, '; ' ORDER BY it.tag_code), '')::varchar AS tags_string
FROM issues i
JOIN locations loc ON i.location_code = loc.code
JOIN users u ON i.creator_id = u.id
LEFT JOIN users res ON i.resolver_id = res.id
LEFT JOIN issue_tags it ON it.issue_id = i.id
WHERE ($1::varchar IS NULL OR i.status = $1)
  AND ($2::varchar IS NULL OR i.category = $2)
  AND ($3::varchar IS NULL OR i.location_code = $3)
GROUP BY i.id, loc.code, loc.name_vi, loc.name_zh, loc.name_en, u.id, res.id
ORDER BY i.created_at DESC
LIMIT 100000
`

type ListIssuesForExportParams struct {
	Status       sql.NullString
	Category     sql.NullString
	LocationCode sql.NullString
}

type ListIssuesForExportRow struct {
	ID               int64
	ClientUuid       string
	Category         string
	LocationCode     string
	LocationNameVi   string
	LocationNameZh   string
	LocationNameEn   string
	Status           string
	Description      sql.NullString
	RejectReason     sql.NullString
	CreatorUsername  string
	CreatorFullName  string
	ResolverUsername sql.NullString
	ResolverFullName sql.NullString
	ScoreRating      sql.NullInt16
	CreatedAt        time.Time
	ResolvedAt       sql.NullTime
	ClosedAt         sql.NullTime
	TagsString       string
}

func (q *Queries) ListIssuesForExport(ctx context.Context, arg ListIssuesForExportParams) ([]ListIssuesForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesForExport, arg.Status, arg.Category, arg.LocationCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesForExportRow
	for rows.Next() {
		var i ListIssuesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientUuid,
			&i.Category,
			&i.LocationCode,
			&i.LocationNameVi,
			&i.LocationNameZh,
			&i.LocationNameEn,
			&i.Status,
			&i.Description,
			&i.RejectReason,
			&i.CreatorUsername,
			&i.CreatorFullName,
			&i.ResolverUsername,
			&i.ResolverFullName,
			&i.ScoreRating,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.TagsString,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at FROM locations
WHERE is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.QrCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOverdueIssues = `-- name: ListOpenOverdueIssues :many
SELECT id, location_code, created_at
FROM issues
WHERE status = 'OPEN'
  AND created_at < CURRENT_TIMESTAMP - INTERVAL '48 hours'
ORDER BY id ASC
`

type ListOpenOverdueIssuesRow struct {
	ID           int64
	LocationCode string
	CreatedAt    time.Time
}

func (q *Queries) ListOpenOverdueIssues(ctx context.Context) ([]ListOpenOverdueIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenOverdueIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenOverdueIssuesRow
	for rows.Next() {
		var i ListOpenOverdueIssuesRow
		if err := rows.Scan(&i.ID, &i.LocationCode, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many

SELECT code, description, is_system FROM permissions
ORDER BY code ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Code, &i.Description, &i.IsSystem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT role, permission_code
FROM role_permissions
ORDER BY role ASC, permission_code ASC
`

func (q *Queries) ListRolePermissions(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.Role, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreLogsByIssue = `-- name: ListScoreLogsByIssue :many
SELECT sl.id, sl.issue_id, sl.target_type, sl.target_id, sl.rule_key, sl.points, sl.created_at, sl.penalty_date, COALESCE(sr.description, sl.rule_key) AS rule_description
FROM score_logs sl
LEFT JOIN scoring_rules sr ON sl.rule_key = sr.rule_key
WHERE sl.issue_id = $1
ORDER BY sl.id ASC
`

type ListScoreLogsByIssueRow struct {
	ID              int64
	IssueID         int64
	TargetType      string
	TargetID        string
	RuleKey         string
	Points          int32
	CreatedAt       time.Time
	PenaltyDate     sql.NullTime
	RuleDescription string
}

func (q *Queries) ListScoreLogsByIssue(ctx context.Context, issueID int64) ([]ListScoreLogsByIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listScoreLogsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoreLogsByIssueRow
	for rows.Next() {
		var i ListScoreLogsByIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.TargetType,
			&i.TargetID,
			&i.RuleKey,
			&i.Points,
			&i.CreatedAt,
			&i.PenaltyDate,
			&i.RuleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreLogsByTargetSince = `-- name: ListScoreLogsByTargetSince :many
SELECT sl.id, sl.issue_id, sl.target_type, sl.target_id, sl.rule_key, sl.points, sl.created_at, sl.penalty_date, COALESCE(sr.description, sl.rule_key) AS rule_description,
       COALESCE(i.category, '') AS issue_category,
       COALESCE(i.description, '') AS issue_description,
       COALESCE(i.status, '') AS issue_status
FROM score_logs sl
LEFT JOIN scoring_rules sr ON sl.rule_key = sr.rule_key
LEFT JOIN issues i ON sl.issue_id = i.id
WHERE sl.target_type = $1 AND sl.target_id = $2 AND sl.created_at >= $3
ORDER BY sl.created_at DESC, sl.id DESC
`

type ListScoreLogsByTargetSinceParams struct {
	TargetType string
	TargetID   string
	CreatedAt  time.Time
}

type ListScoreLogsByTargetSinceRow struct {
	ID               int64
	IssueID          int64
	TargetType       string
	TargetID         string
	RuleKey          string
	Points           int32
	CreatedAt        time.Time
	PenaltyDate      sql.NullTime
	RuleDescription  string
	IssueCategory    string
	IssueDescription string
	IssueStatus      string
}

func (q *Queries) ListScoreLogsByTargetSince(ctx context.Context, arg ListScoreLogsByTargetSinceParams) ([]ListScoreLogsByTargetSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listScoreLogsByTargetSince, arg.TargetType, arg.TargetID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoreLogsByTargetSinceRow
	for rows.Next() {
		var i ListScoreLogsByTargetSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.TargetType,
			&i.TargetID,
			&i.RuleKey,
			&i.Points,
			&i.CreatedAt,
			&i.PenaltyDate,
			&i.RuleDescription,
			&i.IssueCategory,
			&i.IssueDescription,
			&i.IssueStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreLogsSince = `-- name: ListScoreLogsSince :many
SELECT id, issue_id, target_type, target_id, rule_key, points, created_at, penalty_date FROM score_logs
WHERE created_at >= $1
ORDER BY id ASC
`

func (q *Queries) ListScoreLogsSince(ctx context.Context, createdAt time.Time) ([]ScoreLog, error) {
	rows, err := q.db.QueryContext(ctx, listScoreLogsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoreLog
	for rows.Next() {
		var i ScoreLog
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.TargetType,
			&i.TargetID,
			&i.RuleKey,
			&i.Points,
			&i.CreatedAt,
			&i.PenaltyDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, code, name_vi, name_zh, name_en, category, use_count, is_preset, is_active FROM tags
WHERE is_active = TRUE
ORDER BY use_count DESC, id ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.Category,
			&i.UseCount,
			&i.IsPreset,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForIssue = `-- name: ListTagsForIssue :many
SELECT t.code, t.name_vi, t.name_zh, t.name_en, t.category
FROM tags t
JOIN issue_tags it ON t.code = it.tag_code
WHERE it.issue_id = $1
`

type ListTagsForIssueRow struct {
	Code     string
	NameVi   string
	NameZh   string
	NameEn   string
	Category string
}

func (q *Queries) ListTagsForIssue(ctx context.Context, issueID int64) ([]ListTagsForIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForIssueRow
	for rows.Next() {
		var i ListTagsForIssueRow
		if err := rows.Scan(
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForIssues = `-- name: ListTagsForIssues :many
SELECT it.issue_id, t.code, t.name_vi, t.name_zh, t.name_en, t.category
FROM tags t
JOIN issue_tags it ON t.code = it.tag_code
WHERE it.issue_id = ANY($1::bigint[])
ORDER BY it.issue_id, t.code
`

type ListTagsForIssuesRow struct {
	IssueID  int64
	Code     string
	NameVi   string
	NameZh   string
	NameEn   string
	Category string
}

func (q *Queries) ListTagsForIssues(ctx context.Context, issueIds []int64) ([]ListTagsForIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForIssues, pq.Array(issueIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForIssuesRow
	for rows.Next() {
		var i ListTagsForIssuesRow
		if err := rows.Scan(
			&i.IssueID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActiveSessions = `-- name: ListUserActiveSessions :many
SELECT id, device_info, created_at, expires_at
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

type ListUserActiveSessionsRow struct {
	ID         int64
	DeviceInfo sql.NullString
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ListUserActiveSessions(ctx context.Context, userID int64) ([]ListUserActiveSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActiveSessionsRow
	for rows.Next() {
		var i ListUserActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceInfo,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE ($1::varchar IS NULL OR assigned_location_code = $1)
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY id ASC
`

type ListUsersParams struct {
	AssignedLocationCode sql.NullString
	IsActive             sql.NullBool
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.AssignedLocationCode, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.AuthSource,
			&i.AdDn,
			&i.PinHash,
			&i.BadgeCode,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.AssignedLocationCode,
			&i.WxUid,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE notification_outbox
SET status = 'FAILED',
    last_error = $1
WHERE id = $2 AND status = 'SENDING'
`

type MarkOutboxFailedParams struct {
	LastError sql.NullString
	ID        int64
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxFailed, arg.LastError, arg.ID)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE notification_outbox
SET status = 'SENT',
    sent_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'SENDING'
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOutboxSent, id)
	return err
}

const patchIssue = `-- name: PatchIssue :one
UPDATE issues
SET category = COALESCE($2, category),
    cause_type = COALESCE($3, cause_type),
    location_code = COALESCE($4, location_code),
    description = COALESCE($5, description),
    photo_before = COALESCE($6, photo_before),
    photo_detail = COALESCE($7, photo_detail),
    version = version + 1
WHERE id = $1
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type PatchIssueParams struct {
	ID           int64
	Category     sql.NullString
	CauseType    sql.NullString
	LocationCode sql.NullString
	Description  sql.NullString
	PhotoBefore  sql.NullString
	PhotoDetail  sql.NullString
}

func (q *Queries) PatchIssue(ctx context.Context, arg PatchIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, patchIssue,
		arg.ID,
		arg.Category,
		arg.CauseType,
		arg.LocationCode,
		arg.Description,
		arg.PhotoBefore,
		arg.PhotoDetail,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const reopenIssue = `-- name: ReopenIssue :one
UPDATE issues
SET status = 'OPEN',
    reject_reason = $2,
    version = version + 1
WHERE id = $1 
  AND status = 'PENDING_REVIEW' 
  AND ($3::int IS NULL OR version = $3)
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type ReopenIssueParams struct {
	ID              int64
	RejectReason    sql.NullString
	ExpectedVersion sql.NullInt32
}

func (q *Queries) ReopenIssue(ctx context.Context, arg ReopenIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, reopenIssue, arg.ID, arg.RejectReason, arg.ExpectedVersion)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const replaceRolePermissions = `-- name: ReplaceRolePermissions :exec
WITH deleted AS (
    DELETE FROM role_permissions WHERE role = $1
)
INSERT INTO role_permissions (role, permission_code)
SELECT $1, permission_code
FROM unnest($2::varchar[]) AS permission_code
ON CONFLICT (role, permission_code) DO NOTHING
`

type ReplaceRolePermissionsParams struct {
	Role    string
	Column2 []string
}

func (q *Queries) ReplaceRolePermissions(ctx context.Context, arg ReplaceRolePermissionsParams) error {
	_, err := q.db.ExecContext(ctx, replaceRolePermissions, arg.Role, pq.Array(arg.Column2))
	return err
}

const resolveIssue = `-- name: ResolveIssue :one
UPDATE issues
SET status = 'PENDING_REVIEW',
    resolver_id = $2,
    photo_after = $3,
    resolved_at = CURRENT_TIMESTAMP,
    version = version + 1
WHERE id = $1 AND status = 'OPEN' AND version = $4
RETURNING id, client_uuid, version, creator_id, resolver_id, category, cause_type, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at
`

type ResolveIssueParams struct {
	ID         int64
	ResolverID sql.NullInt64
	PhotoAfter sql.NullString
	Version    int32
}

func (q *Queries) ResolveIssue(ctx context.Context, arg ResolveIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, resolveIssue,
		arg.ID,
		arg.ResolverID,
		arg.PhotoAfter,
		arg.Version,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.CauseType,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const retryOutboxTask = `-- name: RetryOutboxTask :exec
UPDATE notification_outbox
SET status = 'PENDING',
    retry_count = retry_count + 1,
    last_error = $1,
    next_retry_at = CURRENT_TIMESTAMP + ($2 * INTERVAL '1 second')
WHERE id = $3 AND status = 'SENDING'
`

type RetryOutboxTaskParams struct {
	LastError sql.NullString
	Column2   interface{}
	ID        int64
}

func (q *Queries) RetryOutboxTask(ctx context.Context, arg RetryOutboxTaskParams) error {
	_, err := q.db.ExecContext(ctx, retryOutboxTask, arg.LastError, arg.Column2, arg.ID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeUserRefreshTokens, userID)
	return err
}

const setAllTagsActiveStatus = `-- name: SetAllTagsActiveStatus :exec
UPDATE tags
SET is_active = $1
`

func (q *Queries) SetAllTagsActiveStatus(ctx context.Context, isActive bool) error {
	_, err := q.db.ExecContext(ctx, setAllTagsActiveStatus, isActive)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name_vi = $2,
    name_zh = $3,
    name_en = $4,
    qr_code = $5
WHERE code = $1
RETURNING id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at
`

type UpdateLocationParams struct {
	Code   string
	NameVi string
	NameZh string
	NameEn string
	QrCode string
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.Code,
		arg.NameVi,
		arg.NameZh,
		arg.NameEn,
		arg.QrCode,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.QrCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateLocationActiveStatus = `-- name: UpdateLocationActiveStatus :one
UPDATE locations
SET is_active = $2
WHERE code = $1
RETURNING id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at
`

type UpdateLocationActiveStatusParams struct {
	Code     string
	IsActive bool
}

func (q *Queries) UpdateLocationActiveStatus(ctx context.Context, arg UpdateLocationActiveStatusParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocationActiveStatus, arg.Code, arg.IsActive)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.QrCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateTagActiveStatus = `-- name: UpdateTagActiveStatus :one
UPDATE tags
SET is_active = $2
WHERE code = $1
RETURNING id, code, name_vi, name_zh, name_en, category, use_count, is_preset, is_active
`

type UpdateTagActiveStatusParams struct {
	Code     string
	IsActive bool
}

func (q *Queries) UpdateTagActiveStatus(ctx context.Context, arg UpdateTagActiveStatusParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTagActiveStatus, arg.Code, arg.IsActive)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.Category,
		&i.UseCount,
		&i.IsPreset,
		&i.IsActive,
	)
	return i, err
}

const updateUserADLogin = `-- name: UpdateUserADLogin :one
UPDATE users
SET full_name = $2,
    email = $3,
    role = $4,
    last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at
`

type UpdateUserADLoginParams struct {
	ID       int64
	FullName string
	Email    sql.NullString
	Role     string
}

func (q *Queries) UpdateUserADLogin(ctx context.Context, arg UpdateUserADLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserADLogin,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users
SET role = COALESCE($2, role),
    assigned_location_code = COALESCE($3, assigned_location_code),
    is_active = COALESCE($4, is_active)
WHERE id = $1
RETURNING id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at
`

type UpdateUserAdminParams struct {
	ID                   int64
	Role                 string
	AssignedLocationCode sql.NullString
	IsActive             bool
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAdmin,
		arg.ID,
		arg.Role,
		arg.AssignedLocationCode,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const upsertADConfig = `-- name: UpsertADConfig :one
INSERT INTO ad_configs (
    id, is_enabled, server, port, use_tls, skip_tls_verify,
    base_dn, bind_dn, bind_password, user_filter,
    group_admin_dn, group_safety_dn, group_leader_dn,
    updated_at, updated_by
) VALUES (
    1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, CURRENT_TIMESTAMP, $13
)
ON CONFLICT (id) DO UPDATE SET
    is_enabled = EXCLUDED.is_enabled,
    server = EXCLUDED.server,
    port = EXCLUDED.port,
    use_tls = EXCLUDED.use_tls,
    skip_tls_verify = EXCLUDED.skip_tls_verify,
    base_dn = EXCLUDED.base_dn,
    bind_dn = EXCLUDED.bind_dn,
    bind_password = CASE WHEN EXCLUDED.bind_password = '' THEN ad_configs.bind_password ELSE EXCLUDED.bind_password END,
    user_filter = EXCLUDED.user_filter,
    group_admin_dn = EXCLUDED.group_admin_dn,
    group_safety_dn = EXCLUDED.group_safety_dn,
    group_leader_dn = EXCLUDED.group_leader_dn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
RETURNING id, is_enabled, server, port, use_tls, skip_tls_verify, base_dn, bind_dn, bind_password, user_filter, group_admin_dn, group_safety_dn, group_leader_dn, updated_at, updated_by
`

type UpsertADConfigParams struct {
	IsEnabled     bool
	Server        string
	Port          int32
	UseTls        bool
	SkipTlsVerify bool
	BaseDn        string
	BindDn        string
	BindPassword  string
	UserFilter    string
	GroupAdminDn  string
	GroupSafetyDn string
	GroupLeaderDn string
	UpdatedBy     sql.NullInt64
}

func (q *Queries) UpsertADConfig(ctx context.Context, arg UpsertADConfigParams) (AdConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertADConfig,
		arg.IsEnabled,
		arg.Server,
		arg.Port,
		arg.UseTls,
		arg.SkipTlsVerify,
		arg.BaseDn,
		arg.BindDn,
		arg.BindPassword,
		arg.UserFilter,
		arg.GroupAdminDn,
		arg.GroupSafetyDn,
		arg.GroupLeaderDn,
		arg.UpdatedBy,
	)
	var i AdConfig
	err := row.Scan(
		&i.ID,
		&i.IsEnabled,
		&i.Server,
		&i.Port,
		&i.UseTls,
		&i.SkipTlsVerify,
		&i.BaseDn,
		&i.BindDn,
		&i.BindPassword,
		&i.UserFilter,
		&i.GroupAdminDn,
		&i.GroupSafetyDn,
		&i.GroupLeaderDn,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertAIConfig = `-- name: UpsertAIConfig :one
INSERT INTO ai_configs (
    id, is_enabled, base_url, api_key, default_model,
    model_translate, model_vision, model_summary,
    updated_at, updated_by
) VALUES (
    1, $1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP, $8
)
ON CONFLICT (id) DO UPDATE SET
    is_enabled = EXCLUDED.is_enabled,
    base_url = EXCLUDED.base_url,
    api_key = CASE WHEN EXCLUDED.api_key = '' THEN ai_configs.api_key ELSE EXCLUDED.api_key END,
    default_model = EXCLUDED.default_model,
    model_translate = EXCLUDED.model_translate,
    model_vision = EXCLUDED.model_vision,
    model_summary = EXCLUDED.model_summary,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
RETURNING id, is_enabled, base_url, api_key, default_model, model_translate, model_vision, model_summary, updated_at, updated_by
`

type UpsertAIConfigParams struct {
	IsEnabled      bool
	BaseUrl        string
	ApiKey         string
	DefaultModel   string
	ModelTranslate string
	ModelVision    string
	ModelSummary   string
	UpdatedBy      sql.NullInt64
}

func (q *Queries) UpsertAIConfig(ctx context.Context, arg UpsertAIConfigParams) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertAIConfig,
		arg.IsEnabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.DefaultModel,
		arg.ModelTranslate,
		arg.ModelVision,
		arg.ModelSummary,
		arg.UpdatedBy,
	)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.DefaultModel,
		&i.ModelTranslate,
		&i.ModelVision,
		&i.ModelSummary,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertNotificationConfig = `-- name: UpsertNotificationConfig :one
INSERT INTO notification_configs (
    id, wxpusher_enabled, wxpusher_app_token, lan_webhook_url, public_base_url, updated_at, updated_by
) VALUES (
    1, $1, $2, $3, $4, CURRENT_TIMESTAMP, $5
)
ON CONFLICT (id) DO UPDATE SET
    wxpusher_enabled = EXCLUDED.wxpusher_enabled,
    wxpusher_app_token = CASE WHEN EXCLUDED.wxpusher_app_token = '' THEN notification_configs.wxpusher_app_token ELSE EXCLUDED.wxpusher_app_token END,
    lan_webhook_url = CASE WHEN EXCLUDED.lan_webhook_url = '' THEN notification_configs.lan_webhook_url ELSE EXCLUDED.lan_webhook_url END,
    public_base_url = EXCLUDED.public_base_url,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
RETURNING id, wxpusher_enabled, wxpusher_app_token, lan_webhook_url, public_base_url, updated_at, updated_by
`

type UpsertNotificationConfigParams struct {
	WxpusherEnabled  bool
	WxpusherAppToken string
	LanWebhookUrl    string
	PublicBaseUrl    string
	UpdatedBy        sql.NullInt64
}

func (q *Queries) UpsertNotificationConfig(ctx context.Context, arg UpsertNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertNotificationConfig,
		arg.WxpusherEnabled,
		arg.WxpusherAppToken,
		arg.LanWebhookUrl,
		arg.PublicBaseUrl,
		arg.UpdatedBy,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.WxpusherEnabled,
		&i.WxpusherAppToken,
		&i.LanWebhookUrl,
		&i.PublicBaseUrl,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertScoringRule = `-- name: UpsertScoringRule :one
INSERT INTO scoring_rules (
    rule_key, points, description
) VALUES (
    $1, $2, $3
)
ON CONFLICT (rule_key) DO UPDATE SET
    points = EXCLUDED.points,
    description = COALESCE(EXCLUDED.description, scoring_rules.description)
RETURNING id, rule_key, points, description
`

type UpsertScoringRuleParams struct {
	RuleKey     string
	Points      int32
	Description sql.NullString
}

func (q *Queries) UpsertScoringRule(ctx context.Context, arg UpsertScoringRuleParams) (ScoringRule, error) {
	row := q.db.QueryRowContext(ctx, upsertScoringRule, arg.RuleKey, arg.Points, arg.Description)
	var i ScoringRule
	err := row.Scan(
		&i.ID,
		&i.RuleKey,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (
    code, name_vi, name_zh, name_en, category, is_preset
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (code) DO UPDATE SET
    name_vi = EXCLUDED.name_vi,
    name_zh = EXCLUDED.name_zh,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category
RETURNING id, code, name_vi, name_zh, name_en, category, use_count, is_preset, is_active
`

type UpsertTagParams struct {
	Code     string
	NameVi   string
	NameZh   string
	NameEn   string
	Category string
	IsPreset bool
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.Code,
		arg.NameVi,
		arg.NameZh,
		arg.NameEn,
		arg.Category,
		arg.IsPreset,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.Category,
		&i.UseCount,
		&i.IsPreset,
		&i.IsActive,
	)
	return i, err
}

const upsertTranslationCache = `-- name: UpsertTranslationCache :one
INSERT INTO translation_cache (
    content_hash, target_lang, source_text, translated_text
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (content_hash, target_lang) DO UPDATE
SET translated_text = EXCLUDED.translated_text,
    source_text = EXCLUDED.source_text
RETURNING content_hash, target_lang, source_text, translated_text, created_at
`

type UpsertTranslationCacheParams struct {
	ContentHash    string
	TargetLang     string
	SourceText     string
	TranslatedText string
}

func (q *Queries) UpsertTranslationCache(ctx context.Context, arg UpsertTranslationCacheParams) (TranslationCache, error) {
	row := q.db.QueryRowContext(ctx, upsertTranslationCache,
		arg.ContentHash,
		arg.TargetLang,
		arg.SourceText,
		arg.TranslatedText,
	)
	var i TranslationCache
	err := row.Scan(
		&i.ContentHash,
		&i.TargetLang,
		&i.SourceText,
		&i.TranslatedText,
		&i.CreatedAt,
	)
	return i, err
}
