// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const getIssueByUUID = `-- name: GetIssueByUUID :one
SELECT id, client_uuid, version, creator_id, resolver_id, category, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at FROM issues
WHERE client_uuid = $1 LIMIT 1
`

func (q *Queries) GetIssueByUUID(ctx context.Context, clientUuid string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByUUID, clientUuid)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.Version,
		&i.CreatorID,
		&i.ResolverID,
		&i.Category,
		&i.LocationCode,
		&i.Description,
		&i.RejectReason,
		&i.PhotoBefore,
		&i.PhotoDetail,
		&i.PhotoAfter,
		&i.ScoreRating,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getLocationByCode = `-- name: GetLocationByCode :one
SELECT id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at FROM locations
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetLocationByCode(ctx context.Context, code string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByCode, code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameVi,
		&i.NameZh,
		&i.NameEn,
		&i.QrCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, auth_source, ad_dn, pin_hash, badge_code, full_name, email, role, assigned_location_code, wx_uid, is_active, created_at, last_login_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AuthSource,
		&i.AdDn,
		&i.PinHash,
		&i.BadgeCode,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.AssignedLocationCode,
		&i.WxUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, code, name_vi, name_zh, name_en, qr_code, is_active, created_at FROM locations
WHERE is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameVi,
			&i.NameZh,
			&i.NameEn,
			&i.QrCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssues = `-- name: ListOpenIssues :many
SELECT id, client_uuid, version, creator_id, resolver_id, category, location_code, description, reject_reason, photo_before, photo_detail, photo_after, score_rating, status, created_at, resolved_at, closed_at FROM issues
WHERE status = 'OPEN'
ORDER BY created_at DESC
`

func (q *Queries) ListOpenIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listOpenIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ClientUuid,
			&i.Version,
			&i.CreatorID,
			&i.ResolverID,
			&i.Category,
			&i.LocationCode,
			&i.Description,
			&i.RejectReason,
			&i.PhotoBefore,
			&i.PhotoDetail,
			&i.PhotoAfter,
			&i.ScoreRating,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
